hh <- read.table('./household_power_consumption.txt',header = TRUE, sep = ";",na.strings = "?",nrows = 2075259,stringsAsFactors = FALSE)
hh$Date <- as.Date(hh$Date,"%d/%m/%Y")
plot2date <- subset(hh,hh$Date=="2007-02-01"|hh$Date=="2007-02-02") 
datetime <- paste(plot2date$Date,plot2date$Time)
datetime <- as.POSIXct(datetime)
plot(plot2date$Global_active_power ~ datetime,type="l",xlab="",ylab = "Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png",width=480,height=480)
dev.off()
